[package]
name = "pigeon"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.2"
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["compat", "codec"] }
tokio-stream = "0.1.16"
thiserror = "1.0.64"
bevy_ecs = "0.14.2"